import React, { useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import { router, useLocalSearchParams } from "expo-router";
import { api } from "../../../src/api";
import { Button, Card, ErrorBox, Field, Page, Pill } from "../../../src/components";
import { colors } from "../../../src/theme";

export default function UploadDocument() {
  const { id } = useLocalSearchParams();
  const [asset, setAsset] = useState(null); const [title, setTitle] = useState(""); const [documentType, setDocumentType] = useState("Bilirkişi raporu"); const [documentDate, setDocumentDate] = useState(""); const [source, setSource] = useState("UYAP"); const [content, setContent] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function pick() { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain"], copyToCacheDirectory: true, multiple: false }); if (!result.canceled) { const a = result.assets[0]; setAsset(a); if (!title) setTitle(a.name); } }
  async function submit() { setBusy(true); setError(""); try { await api.uploadDocument(id, { title: title || asset?.name || "Belge", documentType, documentDate, source, content }, asset); Alert.alert("Belge işlendi", "Dava stratejisi ve kontrol listesi güncellendi."); router.back(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <Page><Card style={styles.form}>{error ? <ErrorBox message={error} /> : null}<Text style={styles.intro}>PDF, DOCX veya TXT seç. Taranmış ve metni çıkarılamayan belgelerde metni aşağıdaki alana ayrıca yapıştır.</Text><Button title={asset ? "Başka dosya seç" : "Dosya seç"} variant="secondary" onPress={pick} />{asset ? <View style={styles.asset}><Pill tone="success">Seçildi</Pill><View style={{ flex: 1 }}><Text style={styles.name}>{asset.name}</Text><Text style={styles.meta}>{asset.mimeType || "dosya"} · {Math.round((asset.size || 0) / 1024)} KB</Text></View></View> : null}<Field label="Belge başlığı" value={title} onChangeText={setTitle} /><Field label="Belge türü" value={documentType} onChangeText={setDocumentType} placeholder="Tensip, bilirkişi raporu, dilekçe..." /><View style={styles.row}><View style={styles.flex}><Field label="Belge tarihi" value={documentDate} onChangeText={setDocumentDate} placeholder="YYYY-MM-DD" /></View><View style={styles.flex}><Field label="Kaynak" value={source} onChangeText={setSource} /></View></View><Field label="Ek metin / taranmış belge metni" multiline value={content} onChangeText={setContent} placeholder="Dosyadan metin çıkarılamazsa veya ek açıklama gerekiyorsa buraya yapıştır." /><Button title={busy ? "Belge okunuyor ve dava güncelleniyor…" : "Belgeyi işle"} onPress={submit} disabled={busy || (!asset && content.trim().length < 20)} /></Card></Page>;
}
const styles = StyleSheet.create({ form: { gap: 14 }, intro: { color: colors.muted, lineHeight: 22 }, asset: { flexDirection: "row", gap: 12, alignItems: "center", borderWidth: 1, borderColor: colors.line, borderRadius: 13, padding: 13 }, name: { color: colors.ink, fontWeight: "850" }, meta: { color: colors.muted, fontSize: 12, marginTop: 3 }, row: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, flex: { flex: 1, minWidth: 190 } });
